### ISSUE TITLE
Push v0 tag explicitly

### ISSUE THREAD

**Issue by ssssota** [kohei-kohei/alert-aggregator#10]
https://github.com/kohei-kohei/alert-aggregator/blob/dee3d37f5a88f144c6768ac72bb3cdd8a4021581/README.md?plain=1#L49

If you want to use `v0`, you must push the `v0` tag explicitly.

Currently you have pushed `v0.0.1`, we need to use `kohei-kohei/alert-aggregator@v0.0.1`.

**Comment by kohei-kohei** [comment]
thx🌟 

pushed!!
https://github.com/kohei-kohei/alert-aggregator/releases/tag/v0
